# Generated by Django 4.2.16 on 2024-11-19 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoption',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='financial_products.deposit'),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='saving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='financial_products.saving'),
        ),
    ]
