# Generated by Django 4.2.16 on 2024-11-25 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_products', '0002_alter_deposit_joined_users_alter_saving_joined_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saving',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
