# Generated by Django 4.2.16 on 2024-11-21 05:56

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', '선택'), ('M', '남성'), ('F', '여성')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.BooleanField(default=False, verbose_name='결혼 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='property',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='자산'),
        ),
    ]
