# Generated by Django 4.2.16 on 2024-11-24 19:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_images/default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
