# Generated by Django 4.2.16 on 2024-11-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='ten_dd_efee_r',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='yy_efee_r',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='bkpr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cur_nm',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cur_unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='deal_bas_r',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kftc_bkpr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kftc_deal_bas_r',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='ttb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='tts',
            field=models.FloatField(),
        ),
    ]
